# syntax=docker/dockerfile:1

FROM debian

ARG TARGETPLATFORM
ARG TARGETARCH
ARG CLAUDE_VERSION

USER 0

RUN --mount=type=cache,id=downloads,target=/var/cache/downloads,sharing=shared\
    download.sh\
    --var "version=${CLAUDE_VERSION}"\
    --var "bucket=claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819"\
    --platform-arch "linux/amd64=x64"\
    --platform-arch "linux/arm64=arm64"\
    --url "https://storage.googleapis.com/{bucket}/claude-code-releases/{version}/linux-{arch}/claude"\
    --checksum-url "https://storage.googleapis.com/{bucket}/claude-code-releases/{version}/manifest.json"\
    --checksum-jq '.platforms["linux-{arch}"] | (.checksum + " " + .binary)'\
    --install-to "/usr/local/bin/"\
    --verify 'claude --version | grep -qF "{version}"'

USER nonroot
WORKDIR /app
