# syntax=docker/dockerfile:1

FROM debian

USER 0
RUN --mount=type=cache,id=apt-cache,target=/var/cache/apt/,sharing=locked\
    --mount=type=cache,id=apt-listscache,target=/var/lib/apt/lists/,sharing=locked\
    apt-get update &&\
    apt-get install -y --no-install-recommends awscli
USER nonroot
WORKDIR /app
