# syntax=docker/dockerfile:1

FROM golang-debian

ARG TARGETPLATFORM TARGETARCH
USER 0

COPY --from=rover /usr/local/bin/rover /usr/local/bin/

ENV BUN_INSTALL=/bun
ENV PATH="/bun/bin:${PATH}"

RUN mkdir -p /bun/bin
COPY --from=typescript /usr/local/bin/bun /usr/local/bin/
COPY --from=claude /usr/local/bin/claude /usr/local/bin/

WORKDIR /app
