# renovate: datasource=docker depName=golang extractVersion=^alpine(?<version>.+)$ versioning=semver
ALPINE_VERSION=3.22
ALPINE_MIRRORS=https://mirror.netcologne.de/alpine,https://mirror.leaseweb.com/alpine
ALPINE_REPOS=main,community

# renovate: datasource=docker depName=golang versioning=regex:^(?<major>trixie|bookworm|bullseye)$
DEBIAN_RELEASE=trixie

# renovate: datasource=docker depName=nginxinc/nginx-unprivileged
NGINX_VERSION=1.29

GO_PROXY=https://go.pyck.cloud,direct
GO_VERSION=1.25.4

# renovate: datasource=github-releases depName=oven-sh/bun
BUN_VERSION=1.3.2
# renovate: datasource=github-releases depName=go-delve/delve
DELVE_VERSION=1.26.1
# renovate: datasource=github-releases depName=flutter/flutter
FLUTTER_VERSION=3.38.1
# renovate: datasource=github-releases depName=superfly/flyctl
FLYCTL_VERSION=0.4.21
# renovate: datasource=github-releases depName=cli/cli
GITHUBCLI_VERSION=2.88.1
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
GOTESTSUM_VERSION=1.13.0
# renovate: datasource=github-releases depName=helm/helm
HELM_VERSION=4.1.3
# renovate: datasource=github-releases depName=kubernetes/kubernetes
KUBECTL_VERSION=1.35.2
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize extractVersion=^kustomize/v(?<version>.+)$
KUSTOMIZE_VERSION=5.8.1
# renovate: datasource=node-version depName=node
NODE_VERSION=24.14.0
# renovate: datasource=npm depName=renovate
RENOVATE_VERSION=42.99.0
# renovate: datasource=github-releases depName=apollographql/rover
ROVER_VERSION=0.37.2
# renovate: datasource=github-releases depName=go-task/task
TASKFILE_VERSION=3.49.1
# renovate: datasource=github-releases depName=watchexec/watchexec
WATCHEXEC_VERSION=2.5.0
