ALPINE_VERSION=3.22
ALPINE_MIRRORS=https://mirror.netcologne.de/alpine,https://mirror.leaseweb.com/alpine
ALPINE_REPOS=main,community

DEBIAN_RELEASE=trixie

NGINX_VERSION=1.29

GO_PROXY=https://go.pyck.cloud,direct
GO_VERSION=1.25.3

BUN_VERSION=1.3.2
DELVE_VERSION=1.25.2
FLUTTER_VERSION=3.38.1
NODE_VERSION=24.11.0
GITHUBCLI_VERSION=2.82.1
GOTESTSUM_VERSION=1.13.0
KUBECTL_VERSION=1.34.1
RENOVATE_VERSION=42.8.1
ROVER_VERSION=0.36.2
TASKFILE_VERSION=3.45.5
WATCHEXEC_VERSION=2.3.2
