FROM ghcr.io/pyck-ai/baseimages/alpine:latest

ARG TARGETPLATFORM

# The official binaries are not compatible with alpine due to a missing symbol,
# so we provide a shim for it...
COPY <<EOF /tmp/claude_fix.c
#define _GNU_SOURCE
#include <dirent.h>
#include <sys/syscall.h>
#include <unistd.h>

ssize_t posix_getdents(int fd, void *buf, size_t count) {
    return syscall(SYS_getdents64, fd, buf, count);
}
EOF

RUN gcc -shared -fPIC -o /usr/local/lib/claude_fix.so /tmp/claude_fix.c
ENV LD_PRELOAD=/usr/local/lib/claude_fix.so

# Install claude code
ARG CLAUDE_VERSION
RUN /download.sh\
    --var "version=${CLAUDE_VERSION}"\
    --var "bucket=claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819"\
    --platform-arch "linux/amd64=x64"\
    --platform-arch "linux/arm64=arm64"\
    --url "https://storage.googleapis.com/{bucket}/claude-code-releases/{version}/{os}-{arch}-musl/claude"\
    --checksum-url "https://storage.googleapis.com/{bucket}/claude-code-releases/{version}/manifest.json"\
    --checksum-jq '.platforms["{os}-{arch}-musl"] | (.checksum + " " + .binary)'\
    --install-paths "claude"\
    --install-to "/usr/local/bin/"\
    --verify 'claude --version | grep -qF "{version}"'


