#!/usr/bin/env dart
// Dart port of pyck's `workflowgen`.
//
// Two modes:
//   --scaffold  Parse BPMN user tasks (annotated with "ID: WidgetName") and
//               sync flutter/index.rfwtxt files — adds missing widgets,
//               warns about orphans.
//   (default)   Stitch all *.rfwtxt files into dist/widgets.rfwtxt.
//
// Usage:
//   dart run workflowgen.dart "workflows/**/*.rfwtxt"
//   dart run workflowgen.dart --scaffold "workflows/**/*.bpmn"
//   dart run workflowgen.dart -v --dry-run "workflows/**"

import 'dart:io';

import 'package:glob/glob.dart';
import 'package:glob/list_local_fs.dart';
import 'package:path/path.dart' as p;

late bool verbose;
late bool dryRun;
late bool scaffoldMode;

void usage() {
  stderr.writeln(
    'Usage: workflowgen [-v] [--dry-run] [--scaffold] <glob>...\n\n'
    '  <glob>      glob pattern for file discovery\n'
    '              stitch mode:   "workflows/**/flutter/*.rfwtxt"\n'
    '              scaffold mode: "workflows/**/*.bpmn"\n'
    '  --scaffold  sync flutter/index.rfwtxt with BPMN user tasks\n'
    '  -v          verbose output\n'
    '  --dry-run   print output without writing files',
  );
  exit(1);
}

class RfwComponent {
  final String id;
  final String content;
  RfwComponent(this.id, this.content);
}

class WorkflowComponents {
  final String workflowName;
  final String bpmnFile;
  final String rfwFile;
  List<RfwComponent> components;
  WorkflowComponents(this.workflowName, this.bpmnFile, this.rfwFile, this.components);
}

class UserTask {
  final String id;
  final String name;
  final String bpmnFile;
  UserTask(this.id, this.name, this.bpmnFile);
}

// ---------------------------------------------------------------------------
// File discovery
// ---------------------------------------------------------------------------

List<String> findFiles(List<String> patterns, String extension) {
  final files = <String>{};
  for (final pattern in patterns) {
    final pat = pattern.endsWith(extension) ? pattern : '$pattern/**/*$extension';
    final glob = Glob(pat);
    Iterable<FileSystemEntity> entities;
    try {
      entities = glob.listSync();
    } catch (_) {
      continue;
    }
    for (final entity in entities) {
      if (entity is! File) continue;
      final path = entity.path;
      if (path.contains('${p.separator}dist${p.separator}') || path.contains('/dist/')) {
        continue;
      }
      files.add(path);
    }
  }
  final list = files.toList()..sort();
  return list;
}

// ---------------------------------------------------------------------------
// RFW parsing
// ---------------------------------------------------------------------------

final widgetRe = RegExp(r'^widget\s+(\w+)\s*=');
final importRe = RegExp(r'^import\s+([^;]+);');

class ParsedRfw {
  final List<RfwComponent> components;
  final List<String> imports;
  final String header;
  ParsedRfw(this.components, this.imports, this.header);
}

ParsedRfw parseRfwFile(String rfwFile) {
  final content = File(rfwFile).readAsStringSync();
  final lines = content.split('\n');

  final imports = <String>[];
  final components = <RfwComponent>[];
  final headerLines = <String>[];
  ({String id, List<String> lines})? current;

  for (final line in lines) {
    final impMatch = importRe.firstMatch(line);
    if (impMatch != null) {
      imports.add(impMatch.group(1)!.trim());
      if (components.isEmpty && current == null) headerLines.add(line);
      continue;
    }

    final widgetMatch = widgetRe.firstMatch(line);
    if (widgetMatch != null) {
      if (current != null) {
        components.add(RfwComponent(current.id, current.lines.join('\n')));
      }
      current = (id: widgetMatch.group(1)!, lines: <String>[line]);
      continue;
    }

    if (current != null) {
      current.lines.add(line);
      if (line.trim() == ');') {
        components.add(RfwComponent(current.id, current.lines.join('\n')));
        current = null;
      }
    } else if (components.isEmpty) {
      final trimmed = line.trim();
      if (trimmed.isNotEmpty &&
          !trimmed.startsWith('// AUTO-GENERATED') &&
          !trimmed.startsWith('// Generated by') &&
          !trimmed.startsWith('// Source:')) {
        headerLines.add(line);
      } else if (headerLines.isNotEmpty) {
        headerLines.add(line);
      }
    }
  }

  if (current != null) {
    components.add(RfwComponent(current.id, current.lines.join('\n')));
  }

  while (headerLines.isNotEmpty && headerLines.last.trim().isEmpty) {
    headerLines.removeLast();
  }

  return ParsedRfw(components, imports, headerLines.join('\n'));
}

// ---------------------------------------------------------------------------
// Workflow name / BPMN file lookup
// ---------------------------------------------------------------------------

String extractWorkflowName(String rfwPath) {
  var dir = p.dirname(rfwPath);
  for (var i = 0; i < 5; i++) {
    try {
      final hasBpmn = Directory(dir)
          .listSync(followLinks: false)
          .whereType<File>()
          .any((f) => f.path.endsWith('.bpmn'));
      if (hasBpmn) return p.basename(dir);
    } catch (_) {}
    final parent = p.dirname(dir);
    if (parent == dir) break;
    dir = parent;
  }
  return p.basename(p.dirname(p.dirname(rfwPath)));
}

String findBpmnFile(String rfwPath) {
  var dir = p.dirname(rfwPath);
  for (var i = 0; i < 5; i++) {
    try {
      for (final entity in Directory(dir).listSync(followLinks: false)) {
        if (entity is File && entity.path.endsWith('.bpmn')) return entity.path;
      }
    } catch (_) {}
    final parent = p.dirname(dir);
    if (parent == dir) break;
    dir = parent;
  }
  return '';
}

// ---------------------------------------------------------------------------
// BPMN parsing (for scaffold mode)
// ---------------------------------------------------------------------------

final textAnnotationRe = RegExp(
  r'<bpmn:textAnnotation\s+id="([^"]+)"[^>]*>\s*<bpmn:text>([\s\S]*?)</bpmn:text>\s*</bpmn:textAnnotation>',
);
final associationRe = RegExp(
  r'<bpmn:association[^>]*sourceRef="([^"]+)"[^>]*targetRef="([^"]+)"',
);
final userTaskRe = RegExp(r'<bpmn:userTask\s+id="([^"]+)"\s+name="([^"]+)"');

List<UserTask> parseBpmnUserTasks(String bpmnPath) {
  final content = File(bpmnPath).readAsStringSync();

  final annotations = <String, String>{};
  for (final m in textAnnotationRe.allMatches(content)) {
    annotations[m.group(1)!] = m.group(2)!.trim();
  }

  final associations = <String, String>{};
  for (final m in associationRe.allMatches(content)) {
    associations[m.group(1)!] = m.group(2)!;
  }

  final tasks = <UserTask>[];
  for (final m in userTaskRe.allMatches(content)) {
    final taskId = m.group(1)!;
    final taskName = m.group(2)!;
    final annotationId = associations[taskId];
    if (annotationId == null) continue;
    final text = annotations[annotationId];
    if (text == null) continue;
    final componentId = extractComponentId(text);
    if (componentId.isEmpty) continue;
    tasks.add(UserTask(componentId, taskName, bpmnPath));
  }

  if (verbose) {
    print('Found ${tasks.length} annotated user task(s) in $bpmnPath:');
    for (final t in tasks) print('  - ${t.id}: ${t.name}');
  }

  return tasks;
}

String extractComponentId(String text) {
  final idx = text.indexOf('ID:');
  if (idx == -1) return '';
  var id = text.substring(idx + 3).trim();
  final nl = id.indexOf(RegExp(r'[\r\n]'));
  if (nl != -1) id = id.substring(0, nl);
  return id.trim();
}

// ---------------------------------------------------------------------------
// Scaffold: sync BPMN user tasks → flutter/index.rfwtxt
// ---------------------------------------------------------------------------

String scaffoldTemplate(UserTask task) =>
    '// User Task: ${task.name}\n'
    '// Source: ${task.bpmnFile}\n'
    'widget ${task.id} = ActivityContainer(\n'
    '    child: ListView(\n'
    '        children: [\n'
    '          ActivityHeader(title: "${task.name}"),\n'
    '          // TODO: Implement UI for ${task.name}\n'
    '          OutlinedButton(text: "Next [DEBUG]", onPressed: event "next" { }),\n'
    '        ]\n'
    '    )\n'
    ');';

void scaffold(List<String> patterns) {
  final bpmnFiles = findFiles(patterns, '.bpmn');
  if (bpmnFiles.isEmpty) {
    print('No BPMN files found');
    return;
  }

  var totalAdded = 0;
  var totalOrphaned = 0;

  for (final bpmnFile in bpmnFiles) {
    final rfwFile = p.join(p.dirname(bpmnFile), 'flutter', 'index.rfwtxt');
    if (verbose) print('\nSyncing $rfwFile with $bpmnFile...');

    final userTasks = parseBpmnUserTasks(bpmnFile);
    if (userTasks.isEmpty) continue;

    var existing = <RfwComponent>[];
    var header = 'import core.widgets;\nimport local;';
    if (File(rfwFile).existsSync()) {
      final parsed = parseRfwFile(rfwFile);
      existing = parsed.components;
      if (parsed.header.isNotEmpty) header = parsed.header;
    }

    final existingMap = {for (final c in existing) c.id: c};
    final bpmnMap = {for (final t in userTasks) t.id: t};

    final toAdd = userTasks.where((t) => !existingMap.containsKey(t.id)).toList();
    final toKeep = existing.where((c) => bpmnMap.containsKey(c.id)).toList();
    final orphaned = existing.where((c) => !bpmnMap.containsKey(c.id)).toList();

    if (verbose) {
      if (toAdd.isNotEmpty) {
        print('  Adding ${toAdd.length} component(s):');
        for (final t in toAdd) print('    + ${t.id} (${t.name})');
      }
      if (toKeep.isNotEmpty) {
        print('  Preserving ${toKeep.length} existing component(s)');
      }
    }

    if (orphaned.isNotEmpty) {
      stderr.writeln('  WARNING: ${orphaned.length} orphaned widget(s) not linked to BPMN:');
      for (final c in orphaned) stderr.writeln('    ! ${c.id}');
    }

    final taskOrder = {for (var i = 0; i < userTasks.length; i++) userTasks[i].id: i};
    final allComponents = <({String id, String content, int order})>[];
    for (final c in toKeep) {
      allComponents.add((id: c.id, content: c.content, order: taskOrder[c.id] ?? 999));
    }
    for (final t in toAdd) {
      allComponents.add((id: t.id, content: scaffoldTemplate(t), order: taskOrder[t.id] ?? 999));
    }
    allComponents.sort((a, b) => a.order.compareTo(b.order));

    final lines = <String>[header, ''];
    for (final c in allComponents) {
      lines.add(c.content);
      lines.add('');
    }
    for (final c in orphaned) {
      lines.add(c.content);
      lines.add('');
    }
    final output = lines.join('\n');

    if (dryRun) {
      print('=== Generated $rfwFile (dry-run) ===');
      print(output);
      print('=== End ===');
    } else {
      Directory(p.dirname(rfwFile)).createSync(recursive: true);
      File(rfwFile).writeAsStringSync(output);
      if (verbose) print('  Wrote $rfwFile');
    }

    totalAdded += toAdd.length;
    totalOrphaned += orphaned.length;
  }

  if (verbose) {
    print('\nScaffold summary: added $totalAdded, orphaned $totalOrphaned');
  }
}

// ---------------------------------------------------------------------------
// Stitch: combine all *.rfwtxt → dist/widgets.rfwtxt
// ---------------------------------------------------------------------------

const defaultImports = ['core.widgets', 'local'];

void stitch(List<String> patterns) {
  final rfwFiles = findFiles(patterns, '.rfwtxt');

  if (rfwFiles.isEmpty) {
    if (verbose) print('No RFW component files found');
    return;
  }

  if (verbose) print('Found ${rfwFiles.length} RFW component file(s) to stitch');

  final allImports = <String>{...defaultImports};
  final workflows = <WorkflowComponents>[];

  for (final rfwFile in rfwFiles) {
    final parsed = parseRfwFile(rfwFile);
    if (parsed.components.isNotEmpty) {
      final workflowName = extractWorkflowName(rfwFile);
      final bpmnFile = findBpmnFile(rfwFile);
      workflows.add(WorkflowComponents(workflowName, bpmnFile, rfwFile, parsed.components));
      allImports.addAll(parsed.imports);
      if (verbose) {
        print('  - $workflowName: ${parsed.components.length} component(s) from $rfwFile');
      }
    }
  }

  workflows.sort((a, b) => a.workflowName.compareTo(b.workflowName));

  final seen = <String, ({String workflowName, String content})>{};
  var duplicatesSkipped = 0;

  for (final wf in workflows) {
    final kept = <RfwComponent>[];
    for (final comp in wf.components) {
      final existing = seen[comp.id];
      if (existing != null) {
        duplicatesSkipped++;
        if (existing.content != comp.content) {
          stderr.writeln(
            'WARNING: Widget "${comp.id}" defined in both ${existing.workflowName} '
            'and ${wf.workflowName} with different content '
            '(keeping ${existing.workflowName})',
          );
        }
        continue;
      }
      seen[comp.id] = (workflowName: wf.workflowName, content: comp.content);
      kept.add(comp);
    }
    wf.components = kept;
  }

  final sortedImports = allImports.toList()..sort();
  final lines = <String>['// Code generated by workflowgen, DO NOT EDIT.', ''];
  for (final imp in sortedImports) lines.add('import $imp;');

  for (final wf in workflows) {
    if (wf.components.isEmpty) continue;
    lines.add('');
    final n = wf.components.length;
    lines.add('// Workflow: ${wf.workflowName} ($n component${n != 1 ? 's' : ''})');
    lines.add('// Source: ${wf.rfwFile}');
    for (final comp in wf.components) {
      lines.add(comp.content);
      lines.add('');
    }
  }

  final output = lines.join('\n');

  if (dryRun) {
    print('=== Generated dist/widgets.rfwtxt (dry-run) ===');
    print(output);
    print('=== End ===');
    return;
  }

  const outputPath = 'dist/widgets.rfwtxt';
  Directory('dist').createSync(recursive: true);
  File(outputPath).writeAsStringSync(output);

  final totalComponents = workflows.fold<int>(0, (n, w) => n + w.components.length);
  if (verbose) {
    print('\nSuccessfully generated $outputPath');
    print('  Total workflows: ${workflows.length}');
    print('  Unique components: $totalComponents');
    if (duplicatesSkipped > 0) print('  Duplicates skipped: $duplicatesSkipped');
  }
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

void main(List<String> args) {
  // When invoked from the docker entrypoint, dart runs out of
  // /opt/rfw-validator (for pub deps) but globs/dist-output need to resolve
  // against the caller's mounted workspace. The entrypoint exports
  // WORKFLOWGEN_PWD for this.
  final pwd = Platform.environment['WORKFLOWGEN_PWD'];
  if (pwd != null && pwd.isNotEmpty) {
    Directory.current = pwd;
  }

  verbose = args.contains('-v');
  dryRun = args.contains('--dry-run');
  scaffoldMode = args.contains('--scaffold');
  final globs = args.where((a) => !a.startsWith('-')).toList();

  if (globs.isEmpty) usage();

  if (scaffoldMode) {
    scaffold(globs);
  } else {
    stitch(globs);
  }
}
