worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /tmp/nginx.pid;

load_module  modules/ngx_otel_module.so;

events {
    worker_connections  1024;
}

http {
    proxy_temp_path        /tmp/proxy_temp;
    client_body_temp_path  /tmp/client_temp;
    fastcgi_temp_path      /tmp/fastcgi_temp;
    uwsgi_temp_path        /tmp/uwsgi_temp;
    scgi_temp_path         /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile           on;
    tcp_nodelay        on;
    keepalive_timeout  65;

    gzip             on;
    gzip_vary        on;
    gzip_min_length  1024;
    gzip_types       text/plain text/css application/javascript application/json application/xml image/svg+xml;


    log_format  main '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    log_format  json escape=json '{'
        '"time": "${time_iso8601}Z",'

        '"otel_parent_id":"$otel_parent_id",'
        '"otel_parent_sampled":"$otel_parent_sampled",'
        '"otel_trace_id":"$otel_trace_id",'
        '"otel_span_id":"$otel_span_id",'

        '"remote_addr":"$remote_addr",'
        '"remote_port":"$remote_port",'
        '"remote_user":"$remote_user",'
        
        '"request_time":"$request_time",'
        '"request_method": "$request_method",'
        '"request_uri": "$request_uri",'
        '"request_path": "$uri",'
        '"request_args": "$args",'
        '"request_length":"$request_length",'
        '"request_content_length":"$content_length",'
        '"request_content_type":"$content_type",'
        '"request_referer":"$http_referer",'
        '"request_user_agent":"$http_user_agent",'
        '"request_x_forwarded_for":"$http_x_forwarded_for",'

        '"response_status":"$status",'
        '"response_bytes_sent":"$bytes_sent",'

        '"server_name":"$server_name",'
        '"server_addr":"$server_addr",'
        '"server_port":"$server_port",'
        '"server_protocol":"$server_protocol",'

        '"upstream_response_time":"$upstream_response_time",'
        '"upstream_addr":"$upstream_addr",'
        '"upstream_status":"$upstream_status"'
    '}';

     access_log  /var/log/nginx/access.log json;

     include  /etc/nginx/conf.d/*.conf;
}
