# This configuration enables OpenTelemetry tracing for NGINX.
# It exports traces to a local OpenTelemetry Collector running on localhost:4317.
#
# See: https://github.com/nginxinc/nginx-otel

otel_exporter {
    endpoint  localhost:4317;
}

otel_trace  off;

server {
    location / {
        otel_trace  $otel_parent_sampled;
        otel_trace_context  propagate;
    }
}
