# syntax=docker/dockerfile:1

ARG BUN_VERSION=1

#===============================================================================
# DOWNLOADS
#===============================================================================

FROM base AS bun
ARG TARGETPLATFORM TARGETARCH BUN_VERSION
RUN --mount=type=cache,id=downloads,target=/var/cache/downloads,sharing=shared\
    download.sh\
    --var "version=${BUN_VERSION}"\
    --platform-arch "linux/amd64=x64"\
    --platform-arch "linux/arm64=aarch64"\
    --url "https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-linux-{arch}.zip"\
    --checksum-url "https://github.com/oven-sh/bun/releases/download/bun-v{version}/SHASUMS256.txt"\
    --install-paths "bun-linux-{arch}/bun"\
    --install-to "/usr/local/bin/"\
    --verify "bun --version | grep -qF '{version}'"

#===============================================================================
# RESULT
#===============================================================================

FROM base
USER root

ENV BUN_INSTALL=/bun
ENV PATH="/bun/bin:${PATH}"

RUN install -d -o nonroot -g nonroot /bun /bun/bin /bun/install /bun/install/global
COPY --from=bun /usr/local/bin/bun /usr/local/bin/

WORKDIR /app
