name: Build Docker Images

on:
  push:
  schedule:
    # Run every night at 4 AM UTC
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.alpine
            image: alpine
            context: .
          - dockerfile: Dockerfile.debian
            image: debian
            context: .
          - dockerfile: Dockerfile.nginx
            image: nginx
            context: .

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: |-
          linux/amd64
          linux/arm64

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: prepare build args
      id: build-args
      run: |
        BUILD_ARGS="$(cat buildargs.conf | grep -v '^#' | grep -v '^\s*$')"
        {
          echo 'build-args<<EOF'
          echo "$BUILD_ARGS"
          echo 'EOF'
        } >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        build-args: ${{ steps.build-args.outputs.build-args }}
        push: ${{ github.event_name != 'pull_request' }}
        platforms: ${{ steps.buildx.outputs.platforms }}
        tags: |-
          ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}:buildcache,mode=max
